defaults : &defaults
  host: localhost
  adapter: postgres
  migration_files_path: "./priv/migrations"
  model_files_path: "./src/models"

development:
  <<: *defaults
  db: peeper_development
  user: postgres
  password: postgres


test:
  <<: *defaults
  db: peeper_test